name: testing
on:
     push:
         branches:
              -master
jobs:
    welcome-user:
         runs-on: ubuntu-latest
         steps:
            -name: checkout repository code
             uses: actions/checkout@v2
            -name: welcome user
             run: echo "welcome to github actions"              